// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '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',
    appId: '1:854006934123:web:42d6f34927e71c79d21f2e',
    messagingSenderId: '854006934123',
    projectId: 'restarther',
    authDomain: 'restarther.firebaseapp.com',
    storageBucket: 'restarther.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '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',
    appId: '1:854006934123:android:4ac834324fe5a066d21f2e',
    messagingSenderId: '854006934123',
    projectId: 'restarther',
    storageBucket: 'restarther.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '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',
    appId: '1:854006934123:ios:9e2db9fb14544280d21f2e',
    messagingSenderId: '854006934123',
    projectId: 'restarther',
    storageBucket: 'restarther.firebasestorage.app',
    iosBundleId: 'com.example.restartHer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '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',
    appId: '1:854006934123:ios:9e2db9fb14544280d21f2e',
    messagingSenderId: '854006934123',
    projectId: 'restarther',
    storageBucket: 'restarther.firebasestorage.app',
    iosBundleId: 'com.example.restartHer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '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',
    appId: '1:854006934123:web:af61ddb65f5c4d9cd21f2e',
    messagingSenderId: '854006934123',
    projectId: 'restarther',
    authDomain: 'restarther.firebaseapp.com',
    storageBucket: 'restarther.firebasestorage.app',
  );

}